version: '3.8'

services:
  video-downloader:
    build: .
    ports:
      - "${PORT:-3031}:${PORT:-3031}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3031}
      - DOMAIN=${DOMAIN:-localhost}
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - YOUTUBE_REDIRECT_URI=${YOUTUBE_REDIRECT_URI}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3031,http://127.0.0.1:3031}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-15}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
    volumes:
      - ./downloads:/app/downloads
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3031}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 